<style>
    div.content {
        background-color: white;
        border: 1px solid rgb(204, 208, 212);
        border-inline-start-width: 4px;
        border-left-color: #7cb6dc;
        box-shadow: rgba(0, 0, 0, 0.15) 0px 1px 4px 0px;
        margin: 5px 0 15px;
        padding: 20px;
    }
</style>
<div class="wrap">
    <h1>
        <?php echo $title; ?>
    </h1>
    <div class="content">
        <?php echo $content; ?>
    </div>
</div>

